/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jdbc.dao.CategoriaDAO;
import jdbc.dao.FornecedorDAO;
import jdbc.dao.Mat_PrimaDAO;
import jdbc.dao.ProdutoDAO;
import jdbc.model.Categoria;
import jdbc.model.Fornecedor;
import jdbc.model.Mat_Prima;
import jdbc.model.Produto;
import jdbc.util.ConnectionFactory;

/**
 *
 * @author Tigas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        tblProduto.setRowSorter(new TableRowSorter(modelo));
        readTableP();
        
        DefaultTableModel modelo1 = (DefaultTableModel) tblMatPrima.getModel();
        tblMatPrima.setRowSorter(new TableRowSorter(modelo1));
        readTableM();
        
        DefaultTableModel modelo2 = (DefaultTableModel) tblFornecedor.getModel();
        tblFornecedor.setRowSorter(new TableRowSorter(modelo2));
        readTableF();
        
        DefaultTableModel modelo3 = (DefaultTableModel) tblCategoria.getModel();
        tblCategoria.setRowSorter(new TableRowSorter(modelo3));
        readTableC();
    }
    
    private void readTableP(){
        DefaultTableModel modelo = (DefaultTableModel) tblProduto.getModel();
        modelo.setNumRows(0);
        ProdutoDAO produtoDao = new ProdutoDAO();
        for (Produto p: produtoDao.lerBanco()){
            
            modelo.addRow(new Object[]{p.getId(), p.getNome(), p.getDescricao(), p.getQtde(), p.getPreco(),p.getIdCategoria(),p.isTerceiro()});
            
        }
        
    }
    
    private void readTableM(){
        DefaultTableModel modelo = (DefaultTableModel) tblMatPrima.getModel();
        modelo.setNumRows(0);
        Mat_PrimaDAO matPrimaDAO = new Mat_PrimaDAO();
        for (Mat_Prima m: matPrimaDAO.lerBanco()){
            
            modelo.addRow(new Object[]{m.getId(), m.getNome(), m.getDescricao(), m.getQtde(), m.getCusto(),m.getIdFornecedor()});
            
        }
    }
    
    private void readTableF(){
        DefaultTableModel modelo = (DefaultTableModel) tblFornecedor.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        for (Fornecedor f: fornecedorDao.lerBanco()){
            
            modelo.addRow(new Object[]{f.getId(), f.getNome(), f.getDescricao(), f.getCnpj()});
            
        }
    }
    
    private void readTableC(){
        DefaultTableModel modelo = (DefaultTableModel) tblCategoria.getModel();
        modelo.setNumRows(0);
        CategoriaDAO categoriaDao = new CategoriaDAO();
        for (Categoria c: categoriaDao.lerBanco()){
            
            modelo.addRow(new Object[]{c.getId(), c.getNome()});
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlProdutos = new javax.swing.JPanel();
        pnlTblProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        pnlCompProdutos = new javax.swing.JPanel();
        lblProdutoNome = new javax.swing.JLabel();
        txtProdutoNome = new javax.swing.JTextField();
        lblProdutoDes = new javax.swing.JLabel();
        txtProdutoDesc = new javax.swing.JTextField();
        lblProdutoQtde = new javax.swing.JLabel();
        lblProdutoPreco = new javax.swing.JLabel();
        ckTerceirizado = new javax.swing.JCheckBox();
        lblProdutoCategoria = new javax.swing.JLabel();
        btnProdutoInsert = new javax.swing.JButton();
        btnProdutoUpdate = new javax.swing.JButton();
        btnProdutoDelete = new javax.swing.JButton();
        txtProdutoPreco = new javax.swing.JTextField();
        txtProdutoQtde = new javax.swing.JTextField();
        txtProdutoCat = new javax.swing.JTextField();
        pnlMatPrima = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMatPrima = new javax.swing.JTable();
        pnlCompMatPrima = new javax.swing.JPanel();
        lblMatPrimaNome = new javax.swing.JLabel();
        txtMatPrimaNome = new javax.swing.JTextField();
        lblMatPrimaDes = new javax.swing.JLabel();
        txtMatPrimaDesc = new javax.swing.JTextField();
        lblMatPrimaQtde = new javax.swing.JLabel();
        lblMatPrimaCusto = new javax.swing.JLabel();
        txtMatPrimaCusto = new javax.swing.JFormattedTextField();
        lblMatPrimaForne = new javax.swing.JLabel();
        btnMatPrimaInsert = new javax.swing.JButton();
        btnMatPrimaUpdate = new javax.swing.JButton();
        btnMatPrimaDelete = new javax.swing.JButton();
        txtMatPrimaID_Forn = new javax.swing.JTextField();
        txtMatPrimaQtde = new javax.swing.JTextField();
        pnlFornecedores = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblFornNome = new javax.swing.JLabel();
        lblFornDesc = new javax.swing.JLabel();
        lblFornCnpj = new javax.swing.JLabel();
        txtFornNome = new javax.swing.JTextField();
        txtFornDesc = new javax.swing.JTextField();
        btnFornInsert = new javax.swing.JButton();
        btnFornUpdate = new javax.swing.JButton();
        btnFornDelete = new javax.swing.JButton();
        txtFornCnpj = new javax.swing.JTextField();
        pnlCategorias = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCategoria = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblCatNome = new javax.swing.JLabel();
        txtCatNome = new javax.swing.JTextField();
        btnCatInsert = new javax.swing.JButton();
        btnCatUpdate = new javax.swing.JButton();
        btnCatDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Qtde", "Preço", "ID Categoria", "Terceiro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduto);

        javax.swing.GroupLayout pnlTblProdutosLayout = new javax.swing.GroupLayout(pnlTblProdutos);
        pnlTblProdutos.setLayout(pnlTblProdutosLayout);
        pnlTblProdutosLayout.setHorizontalGroup(
            pnlTblProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTblProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTblProdutosLayout.setVerticalGroup(
            pnlTblProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        lblProdutoNome.setText("Nome");

        lblProdutoDes.setText("Descrição");

        lblProdutoQtde.setText("Qtde");

        lblProdutoPreco.setText("Preço (R$)");

        ckTerceirizado.setText("Terceirizado");

        lblProdutoCategoria.setText("ID Categoria");

        btnProdutoInsert.setText("Insert");
        btnProdutoInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoInsertActionPerformed(evt);
            }
        });

        btnProdutoUpdate.setText("Update");
        btnProdutoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoUpdateActionPerformed(evt);
            }
        });

        btnProdutoDelete.setText("Delete");
        btnProdutoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCompProdutosLayout = new javax.swing.GroupLayout(pnlCompProdutos);
        pnlCompProdutos.setLayout(pnlCompProdutosLayout);
        pnlCompProdutosLayout.setHorizontalGroup(
            pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompProdutosLayout.createSequentialGroup()
                        .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdutoNome)
                            .addComponent(txtProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdutoDes)
                            .addComponent(txtProdutoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdutoQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdutoQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdutoPreco)
                            .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ckTerceirizado))
                .addGap(18, 18, 18)
                .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProdutoCat)
                    .addComponent(lblProdutoCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCompProdutosLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnProdutoInsert)
                .addGap(79, 79, 79)
                .addComponent(btnProdutoUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProdutoDelete)
                .addGap(73, 73, 73))
        );
        pnlCompProdutosLayout.setVerticalGroup(
            pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdutoNome)
                    .addComponent(lblProdutoDes)
                    .addComponent(lblProdutoQtde)
                    .addComponent(lblProdutoPreco)
                    .addComponent(lblProdutoCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProdutoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProdutoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProdutoQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProdutoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtProdutoNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckTerceirizado)
                .addGap(36, 36, 36)
                .addGroup(pnlCompProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProdutoInsert)
                    .addComponent(btnProdutoUpdate)
                    .addComponent(btnProdutoDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTblProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCompProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCompProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(pnlTblProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Produtos", pnlProdutos);

        tblMatPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "Qtde", "Custo", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMatPrima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMatPrimaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMatPrima);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblMatPrimaNome.setText("Nome");

        lblMatPrimaDes.setText("Descrição");

        lblMatPrimaQtde.setText("Qtde");

        lblMatPrimaCusto.setText("Custo (R$)");

        txtMatPrimaCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        lblMatPrimaForne.setText("ID Fornecedor");

        btnMatPrimaInsert.setText("Insert");
        btnMatPrimaInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatPrimaInsertActionPerformed(evt);
            }
        });

        btnMatPrimaUpdate.setText("Update");
        btnMatPrimaUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatPrimaUpdateActionPerformed(evt);
            }
        });

        btnMatPrimaDelete.setText("Delete");
        btnMatPrimaDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatPrimaDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCompMatPrimaLayout = new javax.swing.GroupLayout(pnlCompMatPrima);
        pnlCompMatPrima.setLayout(pnlCompMatPrimaLayout);
        pnlCompMatPrimaLayout.setHorizontalGroup(
            pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompMatPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatPrimaNome)
                    .addComponent(txtMatPrimaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatPrimaDes)
                    .addComponent(txtMatPrimaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMatPrimaQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatPrimaQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMatPrimaCusto)
                    .addComponent(txtMatPrimaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMatPrimaForne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMatPrimaID_Forn))
                .addGap(35, 35, 35))
            .addGroup(pnlCompMatPrimaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnMatPrimaInsert)
                .addGap(79, 79, 79)
                .addComponent(btnMatPrimaUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMatPrimaDelete)
                .addGap(71, 71, 71))
        );
        pnlCompMatPrimaLayout.setVerticalGroup(
            pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompMatPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatPrimaNome)
                    .addComponent(lblMatPrimaDes)
                    .addComponent(lblMatPrimaQtde)
                    .addComponent(lblMatPrimaCusto)
                    .addComponent(lblMatPrimaForne))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMatPrimaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMatPrimaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMatPrimaID_Forn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMatPrimaQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMatPrimaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(pnlCompMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMatPrimaInsert)
                    .addComponent(btnMatPrimaUpdate)
                    .addComponent(btnMatPrimaDelete)))
        );

        javax.swing.GroupLayout pnlMatPrimaLayout = new javax.swing.GroupLayout(pnlMatPrima);
        pnlMatPrima.setLayout(pnlMatPrimaLayout);
        pnlMatPrimaLayout.setHorizontalGroup(
            pnlMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCompMatPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMatPrimaLayout.setVerticalGroup(
            pnlMatPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMatPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCompMatPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Matéria Prima", pnlMatPrima);

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Descrição", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFornecedor);

        lblFornNome.setText("Nome");

        lblFornDesc.setText("Descrição");

        lblFornCnpj.setText("CNPJ");

        btnFornInsert.setText("Insert");
        btnFornInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornInsertActionPerformed(evt);
            }
        });

        btnFornUpdate.setText("Update");
        btnFornUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornUpdateActionPerformed(evt);
            }
        });

        btnFornDelete.setText("Delete");
        btnFornDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFornInsert)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFornNome)
                        .addComponent(txtFornNome, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFornDesc)
                            .addComponent(txtFornDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnFornUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornCnpj)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnFornDelete))
                    .addComponent(txtFornCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornNome)
                    .addComponent(lblFornDesc)
                    .addComponent(lblFornCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFornDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFornNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFornCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFornInsert)
                    .addComponent(btnFornUpdate)
                    .addComponent(btnFornDelete))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout pnlFornecedoresLayout = new javax.swing.GroupLayout(pnlFornecedores);
        pnlFornecedores.setLayout(pnlFornecedoresLayout);
        pnlFornecedoresLayout.setHorizontalGroup(
            pnlFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFornecedoresLayout.setVerticalGroup(
            pnlFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fornecedores", pnlFornecedores);

        tblCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoriaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCategoria);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );

        lblCatNome.setText("Nome da categoria:");

        btnCatInsert.setText("Insert");
        btnCatInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatInsertActionPerformed(evt);
            }
        });

        btnCatUpdate.setText("Update");
        btnCatUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatUpdateActionPerformed(evt);
            }
        });

        btnCatDelete.setText("Delete");
        btnCatDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblCatNome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtCatNome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnCatInsert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCatUpdate)
                                .addGap(110, 110, 110)))
                        .addComponent(btnCatDelete)
                        .addGap(30, 30, 30))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblCatNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCatNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCatInsert)
                    .addComponent(btnCatUpdate)
                    .addComponent(btnCatDelete))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnlCategoriasLayout = new javax.swing.GroupLayout(pnlCategorias);
        pnlCategorias.setLayout(pnlCategoriasLayout);
        pnlCategoriasLayout.setHorizontalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCategoriasLayout.setVerticalGroup(
            pnlCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Categorias", pnlCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoInsertActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDAO produtoDao = new ProdutoDAO();
        
        produto.setNome(txtProdutoNome.getText());
        produto.setDescricao(txtProdutoDesc.getText());
        produto.setQtde(Integer.parseInt(txtProdutoQtde.getText()));
        produto.setPreco(Double.parseDouble(txtProdutoPreco.getText()));
        produto.setTerceiro(ckTerceirizado.isSelected());
        produto.setIdCategoria(Integer.parseInt(txtProdutoCat.getText()));
        
        produtoDao.salva(produto);
        
        readTableP();
    }//GEN-LAST:event_btnProdutoInsertActionPerformed

    private void btnProdutoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoUpdateActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDAO produtoDao = new ProdutoDAO();
        if(tblProduto.getSelectedRow() != -1){          
            int linha = tblProduto.getSelectedRow();
            //int coluna = tblProduto.getSelectedColumn();
            Integer id_selecao = (Integer)tblProduto.getValueAt(linha, 0);       
            produto.setId(id_selecao);
            produto.setNome(txtProdutoNome.getText());
            produto.setDescricao(txtProdutoDesc.getText());
            produto.setQtde(Integer.parseInt(txtProdutoQtde.getText()));
            produto.setPreco(Double.parseDouble(txtProdutoPreco.getText()));
            produto.setTerceiro(ckTerceirizado.isSelected());
            produto.setIdCategoria(Integer.parseInt(txtProdutoCat.getText()));
        
            produtoDao.modifica(produto);
            
            readTableP(); 
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
        
    }//GEN-LAST:event_btnProdutoUpdateActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        // TODO add your handling code here:
        if(tblProduto.getSelectedRow() != -1){
            txtProdutoNome.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 1).toString());
            txtProdutoDesc.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 2).toString());
            txtProdutoQtde.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 3).toString());
            txtProdutoPreco.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 4).toString());
            txtProdutoCat.setText(tblProduto.getValueAt(tblProduto.getSelectedRow(), 5).toString());
            if(tblProduto.getValueAt(tblProduto.getSelectedRow(), 6).toString().equals("true")) ckTerceirizado.setSelected(true);
            else ckTerceirizado.setSelected(false);            
        }
        
    }//GEN-LAST:event_tblProdutoMouseClicked

    private void btnProdutoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoDeleteActionPerformed
        // TODO add your handling code here:
        Produto produto = new Produto();
        ProdutoDAO produtoDao = new ProdutoDAO();
        if(tblProduto.getSelectedRow() != -1){          
            int linha = tblProduto.getSelectedRow();
            //int coluna = tblProduto.getSelectedColumn();
            Integer id_selecao = (Integer)tblProduto.getValueAt(linha, 0);       
            produto.setId(id_selecao);
        
            produtoDao.deleta(produto);
            
            readTableP(); 
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnProdutoDeleteActionPerformed

    private void btnMatPrimaInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatPrimaInsertActionPerformed
        // TODO add your handling code here:
        Mat_Prima matPrima = new Mat_Prima();
        Mat_PrimaDAO matPrimaDao = new Mat_PrimaDAO();
        
        matPrima.setNome(txtMatPrimaNome.getText());
        matPrima.setDescricao(txtMatPrimaDesc.getText());
        matPrima.setQtde(Integer.parseInt(txtMatPrimaQtde.getText()));
        matPrima.setCusto(Double.parseDouble(txtMatPrimaCusto.getText()));
        matPrima.setIdFornecedor(Integer.parseInt(txtMatPrimaID_Forn.getText()));
        
        matPrimaDao.salva(matPrima);
        
        readTableM();
    }//GEN-LAST:event_btnMatPrimaInsertActionPerformed

    private void btnMatPrimaUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatPrimaUpdateActionPerformed
        // TODO add your handling code here:
        Mat_Prima matPrima = new Mat_Prima();
        Mat_PrimaDAO matPrimaDao = new Mat_PrimaDAO();
        if(tblMatPrima.getSelectedRow() != -1){          
            int linha = tblMatPrima.getSelectedRow();
            //int coluna = tblMatPrima.getSelectedColumn();
            Integer id_selecao = (Integer)tblMatPrima.getValueAt(linha, 0); 
            matPrima.setId(id_selecao);
            matPrima.setNome(txtMatPrimaNome.getText());
            matPrima.setDescricao(txtMatPrimaDesc.getText());
            matPrima.setQtde(Integer.parseInt(txtMatPrimaQtde.getText()));
            matPrima.setCusto(Double.parseDouble(txtMatPrimaCusto.getText()));
            matPrima.setIdFornecedor(Integer.parseInt(txtMatPrimaID_Forn.getText()));
        
            matPrimaDao.modifica(matPrima);
            
            readTableM(); 
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnMatPrimaUpdateActionPerformed

    private void btnMatPrimaDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatPrimaDeleteActionPerformed
        // TODO add your handling code here:
        Mat_Prima matPrima = new Mat_Prima();
        Mat_PrimaDAO matPrimaDao = new Mat_PrimaDAO();
        if(tblMatPrima.getSelectedRow() != -1){          
            int linha = tblMatPrima.getSelectedRow();
            //int coluna = tblMatPrima.getSelectedColumn();
            Integer id_selecao = (Integer)tblMatPrima.getValueAt(linha, 0);       
            matPrima.setId(id_selecao);
        
            matPrimaDao.deleta(matPrima);
            
            readTableM(); 
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnMatPrimaDeleteActionPerformed

    private void tblMatPrimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMatPrimaMouseClicked
        // TODO add your handling code here:
        if(tblMatPrima.getSelectedRow() != -1){
            txtMatPrimaNome.setText(tblMatPrima.getValueAt(tblMatPrima.getSelectedRow(), 1).toString());
            txtMatPrimaDesc.setText(tblMatPrima.getValueAt(tblMatPrima.getSelectedRow(), 2).toString());
            txtMatPrimaQtde.setText(tblMatPrima.getValueAt(tblMatPrima.getSelectedRow(), 3).toString());
            txtMatPrimaCusto.setText(tblMatPrima.getValueAt(tblMatPrima.getSelectedRow(), 4).toString());
            txtMatPrimaID_Forn.setText(tblMatPrima.getValueAt(tblMatPrima.getSelectedRow(), 5).toString());         
        }
    }//GEN-LAST:event_tblMatPrimaMouseClicked

    private void btnFornInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornInsertActionPerformed
        // TODO add your handling code here:
        Fornecedor fornecedor = new Fornecedor();
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        
        fornecedor.setNome(txtFornNome.getText());
        fornecedor.setDescricao(txtFornDesc.getText());
        fornecedor.setCnpj(txtFornCnpj.getText());
        if(txtFornCnpj.getText().length() > 14 || txtFornCnpj.getText().length() < 14){
            JOptionPane.showMessageDialog(null, "CNPJ inválido!","ERRO!",JOptionPane.ERROR_MESSAGE);
        }else{
            fornecedorDao.salva(fornecedor);
            readTableF();
        }
        
    }//GEN-LAST:event_btnFornInsertActionPerformed

    private void btnFornUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornUpdateActionPerformed
        // TODO add your handling code here:
        Fornecedor fornecedor = new Fornecedor();
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        if(tblFornecedor.getSelectedRow() != -1){          
            int linha = tblFornecedor.getSelectedRow();
            int id_selecao = (Integer)tblFornecedor.getValueAt(linha, 0);
            fornecedor.setId(id_selecao);
            fornecedor.setNome(txtFornNome.getText());
            fornecedor.setDescricao(txtFornDesc.getText());
            fornecedor.setCnpj(txtFornCnpj.getText());
            if(txtFornCnpj.getText().length() > 14 || txtFornCnpj.getText().length() < 14){
                JOptionPane.showMessageDialog(null, "CNPJ inválido!","ERRO!",JOptionPane.ERROR_MESSAGE);
            }else{
                fornecedorDao.modifica(fornecedor);           
                readTableF(); 
            }      
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnFornUpdateActionPerformed

    private void btnFornDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornDeleteActionPerformed
        // TODO add your handling code here:
        Fornecedor fornecedor = new Fornecedor();
        FornecedorDAO fornecedorDao = new FornecedorDAO();
        if(tblFornecedor.getSelectedRow() != -1){          
            int linha = tblFornecedor.getSelectedRow();
            //int coluna = tblMatPrima.getSelectedColumn();
            Integer id_selecao = (Integer)tblFornecedor.getValueAt(linha, 0);       
            fornecedor.setId(id_selecao);
        
            fornecedorDao.deleta(fornecedor);
            
            readTableF(); 
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnFornDeleteActionPerformed

    private void tblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedorMouseClicked
        // TODO add your handling code here:
        if(tblFornecedor.getSelectedRow() != -1){
            txtFornNome.setText(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 1).toString());
            txtFornDesc.setText(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 2).toString());
            txtFornCnpj.setText(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 3).toString());        
        }
    }//GEN-LAST:event_tblFornecedorMouseClicked

    private void btnCatInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatInsertActionPerformed
        // TODO add your handling code here:
        Categoria categoria = new Categoria();
        CategoriaDAO categoriaDao = new CategoriaDAO();
        
        categoria.setNome(txtCatNome.getText());
        categoriaDao.salva(categoria);
        readTableC();
    }//GEN-LAST:event_btnCatInsertActionPerformed

    private void btnCatUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatUpdateActionPerformed
        // TODO add your handling code here:
        Categoria categoria = new Categoria();
        CategoriaDAO categoriaDao = new CategoriaDAO();
        
        if(tblCategoria.getSelectedRow() != -1){
            //txtCatNome.setText(tblCategoria.getValueAt(tblCategoria.getSelectedRow(), 1).toString());
            int linha = tblCategoria.getSelectedRow();
            int id_selecao = (Integer)tblCategoria.getValueAt(linha, 0);
            categoria.setId(id_selecao);
            categoria.setNome(txtCatNome.getText());
            
            categoriaDao.modifica(categoria);
            
            readTableC();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnCatUpdateActionPerformed

    private void btnCatDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatDeleteActionPerformed
        // TODO add your handling code here:
        Categoria categoria = new Categoria();
        CategoriaDAO categoriaDao = new CategoriaDAO();
        
        if(tblCategoria.getSelectedRow() != -1){
            txtCatNome.setText(tblCategoria.getValueAt(tblCategoria.getSelectedRow(), 1).toString());
            int linha = tblCategoria.getSelectedRow();
            int id_selecao = (Integer)tblCategoria.getValueAt(linha, 0);
            categoria.setId(id_selecao);
            
            categoriaDao.deleta(categoria);
            
            readTableC();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um produto!");
        }
    }//GEN-LAST:event_btnCatDeleteActionPerformed

    private void tblCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoriaMouseClicked
        // TODO add your handling code here:
        if(tblCategoria.getSelectedRow() != -1){
            txtCatNome.setText(tblCategoria.getValueAt(tblCategoria.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tblCategoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCatDelete;
    private javax.swing.JButton btnCatInsert;
    private javax.swing.JButton btnCatUpdate;
    private javax.swing.JButton btnFornDelete;
    private javax.swing.JButton btnFornInsert;
    private javax.swing.JButton btnFornUpdate;
    private javax.swing.JButton btnMatPrimaDelete;
    private javax.swing.JButton btnMatPrimaInsert;
    private javax.swing.JButton btnMatPrimaUpdate;
    private javax.swing.JButton btnProdutoDelete;
    private javax.swing.JButton btnProdutoInsert;
    private javax.swing.JButton btnProdutoUpdate;
    private javax.swing.JCheckBox ckTerceirizado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCatNome;
    private javax.swing.JLabel lblFornCnpj;
    private javax.swing.JLabel lblFornDesc;
    private javax.swing.JLabel lblFornNome;
    private javax.swing.JLabel lblMatPrimaCusto;
    private javax.swing.JLabel lblMatPrimaDes;
    private javax.swing.JLabel lblMatPrimaForne;
    private javax.swing.JLabel lblMatPrimaNome;
    private javax.swing.JLabel lblMatPrimaQtde;
    private javax.swing.JLabel lblProdutoCategoria;
    private javax.swing.JLabel lblProdutoDes;
    private javax.swing.JLabel lblProdutoNome;
    private javax.swing.JLabel lblProdutoPreco;
    private javax.swing.JLabel lblProdutoQtde;
    private javax.swing.JPanel pnlCategorias;
    private javax.swing.JPanel pnlCompMatPrima;
    private javax.swing.JPanel pnlCompProdutos;
    private javax.swing.JPanel pnlFornecedores;
    private javax.swing.JPanel pnlMatPrima;
    private javax.swing.JPanel pnlProdutos;
    private javax.swing.JPanel pnlTblProdutos;
    private javax.swing.JTable tblCategoria;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTable tblMatPrima;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCatNome;
    private javax.swing.JTextField txtFornCnpj;
    private javax.swing.JTextField txtFornDesc;
    private javax.swing.JTextField txtFornNome;
    private javax.swing.JFormattedTextField txtMatPrimaCusto;
    private javax.swing.JTextField txtMatPrimaDesc;
    private javax.swing.JTextField txtMatPrimaID_Forn;
    private javax.swing.JTextField txtMatPrimaNome;
    private javax.swing.JTextField txtMatPrimaQtde;
    private javax.swing.JTextField txtProdutoCat;
    private javax.swing.JTextField txtProdutoDesc;
    private javax.swing.JTextField txtProdutoNome;
    private javax.swing.JTextField txtProdutoPreco;
    private javax.swing.JTextField txtProdutoQtde;
    // End of variables declaration//GEN-END:variables
}
